version: "3.7"
services:
    db:
        image: mcr.microsoft.com/mssql/server:2017-latest
        container_name: contoso-sql-server
        environment:
          - SA_PASSWORD=Passw@rd
          - ACCEPT_EULA=Y 
        networks:
            - dbnet
        ports:
            - "1433:1433"

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - 27017:27017

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example

networks:
    dbnet:
        name: dbnet
    mongo:
        name: mongo
